Fix build with gcc-12
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com/Errors/Details/400130

FAILED: CMakeFiles/webos-bluetooth-service.dir/src/bluetoothmapprofileservice.cpp.o
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.bluetooth2/1.0.0-71-r5/recipe-sysroot-native/usr/bin/aarch64-webos-linux/aarch64-webos-linux-g++ -DWBS_LOCAL_SERVICE -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.bluetooth2/1.0.0-71-r5/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.bluetooth2/1.0.0-71-r5/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.bluetooth2/1.0.0-71-r5/recipe-sysroot/usr/include/libmount -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.bluetooth2/1.0.0-71-r5/recipe-sysroot/usr/include/blkid -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.bluetooth2/1.0.0-71-r5/recipe-sysroot/usr/include/gio-unix-2.0 -mcpu=cortex-a72 -march=armv8-a+crc -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.bluetooth2/1.0.0-71-r5/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.bluetooth2/1.0.0-71-r5=/usr/src/debug/com.webos.service.bluetooth2/1.0.0-71-r5                      -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.bluetooth2/1.0.0-71-r5=/usr/src/debug/com.webos.service.bluetooth2/1.0.0-71-r5                      -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.bluetooth2/1.0.0-71-r5/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.bluetooth2/1.0.0-71-r5/recipe-sysroot-native=  -fvisibility-inlines-hidden  -std=c++11 -Wall -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.bluetooth2/1.0.0-71-r5/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.bluetooth2/1.0.0-71-r5/recipe-sysroot/usr/lib/glib-2.0/include -pthread -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.bluetooth2/1.0.0-71-r5/recipe-sysroot/usr/include/libmount -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.bluetooth2/1.0.0-71-r5/recipe-sysroot/usr/include/blkid -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.bluetooth2/1.0.0-71-r5/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.bluetooth2/1.0.0-71-r5/recipe-sysroot/usr/lib/glib-2.0/include -pthread -DUSE_PMLOG_DECLARATION -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.bluetooth2/1.0.0-71-r5/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.bluetooth2/1.0.0-71-r5/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.bluetooth2/1.0.0-71-r5/build/Configured/src -Wl,--no-undefined -DNDEBUG -MD -MT CMakeFiles/webos-bluetooth-service.dir/src/bluetoothmapprofileservice.cpp.o -MF CMakeFiles/webos-bluetooth-service.dir/src/bluetoothmapprofileservice.cpp.o.d -o CMakeFiles/webos-bluetooth-service.dir/src/bluetoothmapprofileservice.cpp.o -c TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.bluetooth2/1.0.0-71-r5/git/src/bluetoothmapprofileservice.cpp
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.bluetooth2/1.0.0-71-r5/git/src/bluetoothmapprofileservice.cpp:28:72: error: variable 'const std::array<std::pair<std::__cxx11::basic_string<char>, BluetoothMapProperty::Type>, 11> filterParam' has initializer but incomplete type
   28 | const std::array<std::pair<std::string,BluetoothMapProperty::Type>,11> filterParam = { std::make_pair("startOffset",BluetoothMapProperty::Type::STARTOFFSET),
      |                                                                        ^~~~~~~~~~~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-8053] CCC: Various build fixes

Change-Id: I20f9ef443be7f63e10e86d03c2d76d84c847cbff